from typing import Dict, List, Optional, Union
import math

# Assuming these are imported from your models file
from models.company_configuration import (
    CompanyContractConfiguration,
    PaymentRules,
    Tier,
    BillingModel
)


class PaymentService:

    @staticmethod
    def _get_alias_for_rule(rule: PaymentRules) -> str:
        """
        Mirrors the exact alias generated by the BigQuery string builder.
        e.g., service_name="ocr" -> "ocr_count"
        """
        if rule.service_name:
            return f"{rule.service_name.value}_count"
        elif rule.event_name:
            return f"{rule.event_name.value}_count"
        return "unknown_count"

    @staticmethod
    def calculate_tiered_cost(total_usage: float, tiers: List[Tier]) -> float:
        """
        The Core Math Engine. Safely slices total usage across an array of tiers.
        Safely handles the "unlimited" string by converting it to infinity.
        """
        remaining_usage = total_usage
        total_cost = 0.0

        # Sort tiers to guarantee they are processed strictly from 0 upwards
        sorted_tiers = sorted(tiers, key=lambda t: t.from_num_actions)

        for tier in sorted_tiers:
            if remaining_usage <= 0:
                break

            # Calculate the maximum capacity of this specific tier
            if tier.up_to_num_actions == "unlimited":
                capacity = float('inf')
            else:
                capacity = tier.up_to_num_actions - tier.from_num_actions

            # How much of our remaining usage fits into this tier?
            usage_in_this_tier = min(remaining_usage, capacity)

            total_cost += (usage_in_this_tier * tier.price_per_unit)
            remaining_usage -= usage_in_this_tier

        return total_cost

    @classmethod
    def calculate_invoice(
            cls,
            bq_results: Dict[str, int],
            contract: CompanyContractConfiguration,
            historical_usage: int = 0
    ) -> dict:
        """
        The Main Router. Directs the database counts to the correct contract logic.
        historical_usage is ONLY required for PREPAID_WITH_OVERAGE models (like Toto/Max).
        """
        billing_model = contract.billing_model
        minimum_fee = contract.minimum_monthly_fee or 0.0
        final_calculated_cost = 0.0
        invoice_status = "SUCCESS"

        # ==========================================================
        # 1. VOLUME TIERED (e.g., Postalbank, Tranzila, Orda)
        # All events are summed together into one giant pool.
        # ==========================================================
        if billing_model == BillingModel.VOLUME_TIERED_WITH_MINIMUM:
            total_combined_usage = 0

            for rule in contract.payment_rules:
                alias = cls._get_alias_for_rule(rule)
                total_combined_usage += bq_results.get(alias, 0)

            # ORDA LOGIC: Check if contract dictates a minimum number of ACTIONS instead of money
            min_actions = contract.minimum_monthly_actions or 0
            billable_usage = max(total_combined_usage, min_actions)

            # Run through the tier math
            primary_tiers = contract.payment_rules[0].tiers
            raw_cost = cls.calculate_tiered_cost(billable_usage, primary_tiers)

            final_calculated_cost = max(raw_cost, minimum_fee)


        # ==========================================================
        # 2. ITEMIZED USAGE (e.g., Isracard, Bizi, Upcapital, Cal, MSE)
        # Includes support for Shared Buckets!
        # ==========================================================
        elif billing_model == BillingModel.ITEMIZED_USAGE_WITH_MINIMUM:
            raw_cost = 0.0
            independent_rules = []
            shared_buckets = {}

            # Group the results based on shared buckets vs independent items
            for rule in contract.payment_rules:
                alias = cls._get_alias_for_rule(rule)
                usage_from_query = bq_results.get(alias, 0)

                if rule.shared_bucket_name:
                    bucket = rule.shared_bucket_name
                    if bucket not in shared_buckets:
                        shared_buckets[bucket] = {"usage": 0, "tiers": rule.tiers}
                    shared_buckets[bucket]["usage"] += usage_from_query
                else:
                    independent_rules.append((usage_from_query, rule.tiers))

            # Math for independent items (e.g., Upcapital's OCR)
            for usage, tiers in independent_rules:
                raw_cost += cls.calculate_tiered_cost(usage, tiers)

            # Math for shared buckets (e.g., Upcapital/Cal's Liveness+FaceMatch pool)
            for bucket_data in shared_buckets.values():
                raw_cost += cls.calculate_tiered_cost(bucket_data["usage"], bucket_data["tiers"])

            final_calculated_cost = max(raw_cost, minimum_fee)


        # ==========================================================
        # 3. SUM MINUS MINIMUM (e.g., IBI)
        # Calculate itemized raw cost, subtract the deductible, charge the floor.
        # ==========================================================
        elif billing_model == BillingModel.SUM_MINUS_MINIMUM:
            raw_cost = 0.0

            for rule in contract.payment_rules:
                alias = cls._get_alias_for_rule(rule)
                usage_for_this_item = bq_results.get(alias, 0)
                raw_cost += cls.calculate_tiered_cost(usage_for_this_item, rule.tiers)

            cost_after_deductible = raw_cost - minimum_fee
            final_calculated_cost = max(cost_after_deductible, minimum_fee)


        # ==========================================================
        # 4. PREPAID WITH OVERAGE (e.g., Toto, Max)
        # Deduct historical usage from the wallet before checking overage.
        # ==========================================================
        elif billing_model == BillingModel.PREPAID_WITH_OVERAGE:
            current_month_usage = 0

            # Sum up all usage for the current month
            for rule in contract.payment_rules:
                alias = cls._get_alias_for_rule(rule)
                current_month_usage += bq_results.get(alias, 0)

            wallet_total = contract.prepaid_action_wallet or 0

            # How many free actions are left from previous months?
            wallet_remaining = max(0, wallet_total - historical_usage)

            # Did they blow past what was left in the wallet this month?
            overage_actions = max(0, current_month_usage - wallet_remaining)

            if overage_actions > 0:
                # TOTO LOGIC: If they don't have a negotiated overage price yet, flag it!
                overage_price = contract.payment_rules[0].overage_price_per_unit

                if overage_price is None:
                    invoice_status = "MANUAL_REVIEW_REQUIRED_NO_OVERAGE_PRICE"
                    final_calculated_cost = 0.0  # Cannot calculate safely
                else:
                    final_calculated_cost = (overage_actions * overage_price) + minimum_fee
            else:
                final_calculated_cost = minimum_fee

        # ==========================================================
        # RETURN FINAL PAYLOAD
        # ==========================================================
        return {
            "billing_model_applied": billing_model.value,
            "invoice_status": invoice_status,
            "raw_database_counts": bq_results,
            "minimum_fee_enforced": minimum_fee,
            "final_invoice_amount": final_calculated_cost,
        }